# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/wifi-revenge"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "http://www.linkedin.com/in/cristiano-giannini-05228b295"

[social.params]
icon = "linkedin"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/cristianogiannini/"

[social.params]
icon = "instagram"

[[social]]
identifier = "discord"
name = "Discord"
url = "https://discord.gg/wk6D8pWh"

[social.params]
icon = "discord"
